config/routes.rb
Cypr::Application.routes.draw do
  get 'admin',  to: "admin#index" 
  get 'logout', to: "users#exit"
  post "login",to: "users#auth"
  post "register", to: "users#register"
  post "restore", to: "users#forgot"
  get "fbregister",to:"users#fbregister"
  scope :path =>"(:locale)", :locale => /ru|ua|en/ do
    root :to => "home#index"
    get "hotels/show/:id" => "hotels#show"
    get "aparts/show/:id" => "aparts#show"
    get "hotels/load_hotels"
    post "hotels/booking/:id" => "hotels#booking"
    post "aparts/booking/:id" => "aparts#booking"
    post "hotels/book/:id" => "hotels#book"
    post "aparts/book/:id" => "aparts#book"

    get "hotels/pay"
    namespace :cabinet do 
        get :profile,to:"profile#show"
        get "offers/remove_photo",to:"offers#remove_photo"
        get "profile/edit",to:"profile#edit"
        put "profile/save",to:"profile#save"
        post "profile/save",to:"profile#save"
        resources :auto
        resources :offers
        resources :aparts
        resources :hotels
    end

    namespace "hotels" do
        %w(complete show booking results get_map_items).each do |action|
            get action
        end
    	post "search"
    	post "book"
    end
    namespace "avia" do
        %w(complete show booking results get_map_items).each do |action|
            get action
        end
        post "search"
        post "book"
    end
    namespace "cars" do
        %w(complete get_map_items show results dropp_off_open_time pick_up_open_time dropp_off_location dropp_off_city dropp_off_country pick_up_location pick_up_city).each do |action|
            get action
        end
    	post "search"
    	post "book"
    end
    get "cars/rules"
    get "cars/show/:id" => "cars#show"
    post "cars/booking/:id" => "cars#booking"
    post "cars/book/:id" => "cars#book"
    post "cars/pay"
    namespace "aparts" do
        %w(complete show results get_map_items).each do |action|
            get action
        end
        get "show/:id" => "aparts#show"
    	post "search"
    	post "book"
    end
    get "faq" ,to:"faq#index"
    get "faq/:seo" ,to:"faq#show"
  end






   namespace :admin do
     post "login_admin"
     post "users/pass_change"
     resources :users
     resources :emails 
     resources :transactions
     resources :facilities
     resources :apartaments
     resources :characteristics
     resources :currencies
     resources :nearbies
          resources :categories
     resources :pages
     get "apartaments",          to: "apartaments#index"
     get "apartaments/delete/:id",      to: "apartaments#delete"
     post "apartaments/upload_photos",  to: "apartaments#upload_photos"
     get "apartaments/remove_photo/:photo_id",  to: "apartaments#remove_photo"
     get "apartaments/remove_employment/:id",  to: "apartaments#remove_employment"
     get "apartaments/remove_price/:id",  to: "apartaments#remove_price"
     get "facilities",          to: "facilities#index"
     get "facilities/new",      to: "facilities#new"
     get "facilities/delete/:id",      to: "facilities#delete"
     get "nearbies/delete/:id",      to: "nearbies#delete"
     get "currencies/delete/:id",      to: "currencies#delete"
     get "characteristics",          to: "characteristics#index"
     get "characteristics/new",      to: "characteristics#new"
     get "characteristics/delete/:id",      to: "characteristics#delete"
     get "settings", to: "settings#index"
     post "settings/save"
   end






  
end

app/models/hotels/hotel.rb
class Hotel < ActiveRecord::Base
   belongs_to :hotel_location
  attr_accessible :image_url,:hotel_location_id, :low_rate,:address, :check_in, :check_out, :currency, :hight_rate, :hotel_id, :lat, :lng, :low_rate, :name, :stars
end

app/models/hotels/hotel_location.rb
class HotelLocation < ActiveRecord::Base
  attr_accessible :code, :lat, :lng, :name,:country_id,:lang,:name_en,:name_ru,:country_id
  has_many :hotels
	def name
	  read_attribute("name_#{I18n.locale}")
	end
  def to_map
  	{
  		lat:self.lat,
  		lng:self.lng,
  		id:self.id,
  		name:self.name,
  	}
  end
end

app/models/search/hotels/hotel_adult.rb
class HotelAdult

  include ActiveAttr::Model
  include ActiveAttrAdditions::Relations

  attribute :first_name,    :type => String 
  attribute :last_name,     :type => String 
  attribute :birth_day,     :type => Integer 
  attribute :birth_month,   :type => Integer 
  attribute :birth_year,    :type => Integer 

  
  def to_api_hash
    hash = {
      :FirstName => self.first_name,
      :LastName  => self.last_name
    }
  end
  
end

app/models/search/hotels/hotel_child.rb
class HotelChild
  
   
  include ActiveAttr::Model
  include ActiveAttrAdditions::Relations

  attribute :age,        :type => Integer , :default => 12


end

app/models/search/hotels/hotel_room.rb
class HotelRoom
  
   
  include ActiveAttr::Model
  include ActiveAttrAdditions::Relations
  attribute :id,        :type => Integer , :default => 1
  attribute :adults,    :type => Integer , :default => 2
  attribute :childs,    :type => Integer , :default => 0
  attribute :child_age, :type => Integer , :default => 12
  nested_attribute :adult, :class_name => "HotelAdult"
  nested_attribute :child, :class_name => "HotelChild"
  
  
  
  def count_adults
    self.adult.size
  end

  def count_childs
    self.child().size
  end
  
  def to_api_hash
    child   =  (1..self.childs).to_a.join(',')
    visitors = self.childs == 0 ? self.adults.to_s : self.adults.to_s + "," + child
  end
  

end

app/models/search/hotels/hotel_search.rb
class HotelSearch
  include ActiveAttr::Model
  include ActiveAttrAdditions::Relations
  
  attribute :city,          :type => String
  attribute :place_code,    :type => String
  attribute :stars,         :type => String 
  attribute :lat,           :type => Float
  attribute :lng,           :type => Float
  attribute :arrival,      :type => Date ,   :default => 2.week.from_now.to_date.strftime("%d.%m.%Y")
  attribute :departure,    :type => Date ,   :default => 1.weeks.from_now.to_date.strftime("%d.%m.%Y")
  attribute :rooms_count,   :type => Integer, :default => 1
  attribute :results_count, :type => Integer, :default => 200
  nested_attribute :rooms,  :class_name => "HotelRoom"
  
  
  def to_api_hash
    search = {}
    self.rooms.each_with_index do  |room,i|
       a = "room#{(i+1)}"
       adults = room.adults.to_s
       childs = room.childs.times.collect{|e| room.child_age }.join(',')
       people = childs.size == 0 ? adults : adults + "," + childs 
       search.merge!(:"#{a}"=>people)
    end
    search.merge!(
      :arrivalDate   => self.departure.strftime("%m/%d/%Y") ,
      :departureDate => self.arrival.strftime("%m/%d/%Y"),
      :results_count => self.results_count,
      :maxStarRating => self.stars,
      :minStarRating => self.stars,
      #:latitude      => self.lat,
      #:longitude     => self.lng,
      :destinationId => self.place_code,
      :searchRadius   => 10,
    )
    search
  end

  def interval
     (arrival - departure).to_i 
  end
  
  def to_title
   "#{self.city}, #{self.departure.strftime('%d.%m.%Y')} - #{self.arrival.strftime('%d.%m.%Y')}"
  end

  def count_people
     count  = 0
    self.rooms.each  do |room|
      count += room.adults
      count += room.childs
    end
    count
  end

end

app/controllers/cabinet/aparts_controller.rb
class Cabinet::ApartsController < ApplicationController

	def index
			
	end	
	def show
		@book = current_user.apartments_bookings.where(id:params[:id].to_i).first
		raise "Booking not found" if @book.nil?
	end
	def edit
		
	end

	private
    def set_layout
      @body_cls = "faq_page cabinet"
      @active_tab  = 1
      @active_link = 0
    end
end

app/controllers/cabinet/auto_controller.rb
class Cabinet::AutoController < ApplicationController

	def index
			
	end	
	def show
		@book = current_user.cars_bookings_payeds.where(id:params[:id].to_i).first
		raise "Booking not found" if @book.nil?
		@rental_terms = api.get_rental_terms @book.pick_location
	end
	def edit
		
	end

	private

    def api
      @api ||= Api::Cars.new(Settings.auto_api.host,Settings.auto_api.user,Settings.auto_api.pass,Settings.auto_api.ip)
    end


    def set_layout
      @body_cls = "faq_page cabinet"
      @active_tab  = 1
      @active_link = 2
    end
end

app/controllers/cabinet/hotels_controller.rb
class Cabinet::HotelsController < ApplicationController

	def index
			
	end	
	def show
		@book = current_user.hotel_booking_payeds.where(id:params[:id].to_i).first
		raise "Booking not found" if @book.nil?
	end
	def edit
		
	end

	private
    def set_layout
      @body_cls = "faq_page cabinet"
      @active_tab  = 1
      @active_link = 1
    end
end

app/controllers/cabinet/houses_controller.rb
class Cabinet::HousesController < UserController
	before_filter :require_login

	def initialize
		super
		@currency = $currency.present? ? Currency.find_by_title($currency.to_s) : Currency.find_by_title('USD')
		@service = 'houses'
		@steps = ['address','facilities','price','details','photos']
	end
	
	def index
		@title = t("cabinet.apart_books")
		@bookings = current_user.apartments_bookings.reverse
	end

	def houses_filter
		# @bookings = ApartmentsBooking.where("created_at > #{Date.strptime(params[:from],"%d.%m.%Y").to_time} AND created_at < #{Date.strptime(params[:to],"%d.%m.%Y").to_time}")
		conditions = {:created_at => Date.strptime(params[:from],"%d.%m.%Y").beginning_of_day..Date.strptime(params[:to],"%d.%m.%Y").end_of_day, :status => [params[:status].split(',')]}
		@bookings = current_user.apartments_bookings.find(:all, :conditions => conditions, :order => 'created_at DESC')
		html = render_to_string partial: 'items'
		render :json => { :html => html, :status => true}
	end

	def show
		@booking = current_user.apartments_bookings.find(params[:id])
		@title = t("cabinet.apart_booking",:number=>@booking.id)
		#raise
		@apartment = @booking.house
	end

	def offers
		@title = t("cabinet.offers")
		@offers = current_user.houses
	end

	def new
		@link_base = ""
		@step = "address"
		@title = t("cabinet.new_add")
		@apartament = House.new
		@apartament.user_id = @apartament.user_id.present? ? @apartament.user_id : @current_user.id 
		@cities = City.all.map{|city| [city.name_ru,city.id]}
		@facilities = Facility.where("active = 1").map{|f| [f.name_ru,f.id,f.ico]} 
		@nearbies = Nearby.all.map{|f| [f.name_ru,f.id,f.ico]} 
	end

	def create
		@apartament = House.new(params[:house])
		@apartament.active = 0
		@apartament.currency_id = @currency.id
		if @apartament.valid?
			@apartament.save
			redirect_to "#{cabinet_house_path(@apartament)}/edit?step=facilities"
		else
			abort
		end
 	end

 	def edit
 		@step = params[:step]
 		@title = t("cabinet.#{@step}")
		@apartament = House.find(params[:id])
		@facilities = Facility.where("active = 1").map{|f| [f.name_ru,f.id]}
		@nearbies   = Nearby.all.map{|f| [f.name_ru,f.id]}
		@link_base = cabinet_house_path(@apartament)
	end

	def delete
		abort
		@apartament = House.find(params[:id])
		@apartament.destroy
		respond_to do |format|
		  format.html { redirect_to "/cabinet/index/offers" }
		  format.xml  { head :ok }
		end
	end

	def update
		next_step_id = @steps.index(params[:step]).to_i

		@apartament = House.find(params[:id])
		if !params[:house].nil?
			if(params[:house][:facilities].present? || params[:house][:nearbies].present?)
				facilities_ids = params[:house][:facilities].keys unless !params[:house][:facilities].present?
				nearbies_ids   = params[:house][:nearbies].present? ? params[:house][:nearbies].keys : [] 
				params[:house].delete(:facilities)
				params[:house].delete(:nearbies)
				@apartament.facilities = Facility.find(facilities_ids) unless facilities_ids.nil?
				@apartament.nearbies   = Nearby.find(nearbies_ids) unless facilities_ids.nil?
			end
		end
		@apartament.update_attributes(params[:house])
		
		if @apartament.valid?
			@apartament.save
			# save_dependencies()
			flash[:notice] = t("apartament.actions.changed")
			if (@steps[next_step_id+1].present?)
				redirect_to "#{cabinet_house_path(@apartament)}/edit?step=#{@steps[next_step_id+1]}"
			else
				redirect_to "/cabinet/index/offers"
			end
		else
			abort
		end
	end

	def upload_photos		
		@photo = Photo.new()
		@photo.house_id = params[:id]
		@photo.file = params[:one_photo]
		
		render :json => {:saved => @photo.save, :id => @photo.id, :path => @photo.file.url(:cabinet)}.to_json
	end

	def delete_photo
		@photo = Photo.find(params[:id])
		@photo.file.destroy
		@photo.delete
		render :text => @photo.delete
	end

	
end

app/controllers/cabinet/messages_controller.rb
class Cabinet::MessagesController < UserController
	include ActionView::Helpers::SanitizeHelper
	before_filter :require_login

	def index
		@messages = current_user.received_messages
		@active   = "inbox"
	end

	def inbox
		@messages = current_user.received_messages
	end

	def outbox
		@messages = current_user.sent_messages
		@active   = "outbox"
	end
	
	def show
		@active  = "new"
		@message = Message.find(params[:id])
		redirect_to :root unless @message.sender == current_user || @message.recepient == current_user
		Message.read_message(@message.id, current_user)
	end

	def new
		@recepient = User.find(params[:recepient_id])
		@apartment = House.find(params[:id])
		@message   = Message.new(:house_id=>@apartment.id)
		@active    = "new"
	end

	def delete
		sleep 1
		message = current_user.received_messages.find(params[:id])
		message.update_attribute(:recipient_deleted,true)
		render :json=>{:success=>true}
	end

	def delete_my
		sleep 1
		message = current_user.sent_messages.find(params[:id])
		message.update_attribute(:sender_deleted,true)
		render :json=>{:success=>true}
	end

	def create
		message = Message.new(params[:message])
		message.body = sanitize(message.body)	
		json = message.save	? {:success=>true,:url=>cabinet_messages_outbox_path} : {:success=>false,:msg=>"error"}
	ensure
		render :json=>json
	end


	
end

app/controllers/cabinet/offers_controller.rb
class Cabinet::OffersController < ApplicationController
    
    def index
    	
    end
	def new
		@offer      = House.new
		@facilities_ids = []
		set_data
	end
	def get_coords address
		data = "http://maps.google.com/maps/api/geocode/json".to_uri.get(address:CGI.unescape(address),sensor:false).deserialize
		if data["status"]!="ZERO_RESULTS"
			data =  data["results"].first["geometry"]["location"]
			{:latitude=>data["lat"],:longitude=>data["lng"]}
		else
			{}
		end
	end
	def create
		facilities = params[:house].delete(:facilities)
		offer  = House.new(params[:house])
		if offer.valid?
			offer.user = current_user
			offer.save
			data = get_coords(offer.full_address)
			offer.update_attributes(data)
			redirect_to edit_cabinet_offer_path(offer.id)
		else
			redirect_to new_cabinet_offer_path
		end

	end
	def edit
		@offer  = current_user.houses.find(params[:id])
		@facilities_ids = @offer.facilities.map(&:id)
		set_data
	end
	def update
		offer  = current_user.houses.find(params[:id])
		facilities =  params[:house].delete(:facilities)[:id].each_pair.map{|f,g| g.to_i == 1 ? f.to_i : nil}.compact
		facilities = Facility.find(facilities)
		offer.update_attributes(params[:house])
		offer.facilities = facilities
		data = get_coords(offer.full_address)
		offer.update_attributes(data)
		offer.save
		redirect_to edit_cabinet_offer_path(offer.id)
	end
	def remove_photo
		json = {:success=>true}
		offer = current_user.houses.find(params[:id])
		photo = offer.photos.find(params[:photo_id])
		photo.delete
	rescue
		json = {:success=>false}
	ensure
		render :json=>json
	end

	private
	def set_data
		@cities     = City.all.map{|c| [c.name,c.id]}
		@countries  = Country.where(id:50).all.map{|c| [c.name,c.id]}
		@facilities = Facility.all.in_groups_of(Facility.count/2)
		@currencies = Currency.all.map{|c| [c.title,c.id]}
		@flat_types = I18n.t("all.flat_types").each_pair.map{|g,h| [h,g.to_s.gsub("type_","")]}
	end
    def set_layout
      @body_cls = "faq_page cabinet offer"
      @active_tab  = 3
      @active_link = 2
    end
end

app/controllers/cabinet/profile_controller.rb
class Cabinet::ProfileController < ApplicationController
	before_filter :require_login
   

	def show
      @active_tab  = 0
      @active_link = 0
      @codes       = Country.get_phones
      @current_code= Country.find_by_code($country_code).country_phone
	end
	def edit
      @active_tab  = 0
      @active_link = 1
	end
  def save
    current_user.update_attributes(params[:user])
    redirect_to "/#{I18n.locale}/cabinet/profile/"
  end
	private
    def set_layout
      @body_cls = "faq_page cabinet"
      @user = current_user
    end
end

app/controllers/cabinet/whishes_controller.rb
class Cabinet::WhishesController < UserController
	before_filter :require_login

	def index
		@title = t("cabinet.whishes")
		@whishes = current_user.wishes
	end
	
	def show
		@title = "#{current_user.first_name} #{current_user.last_name}"
	end


	
end

app/controllers/cabinet_controller.rb
class CabinetController < ApplicationController
	before_filter :require_login

	def initialize
		super
		@currency = Currency.find_by_title($currency.to_s)
	end
	
	def houses
		@title = "Dashboard"
		@bookings = current_user.apartments_bookings

		# per_page = 20
		# sort = params[:sort] || :id
		# @dir = params[:dir] == 'DESC' ? 'ASC' : 'DESC'
		# unless params[:name_ru].nil?
		# 	@apartaments = House.where("name_ru LIKE ?","#{params[:name_ru]}%").paginate(:per_page=>per_page,:page => params[:page]).order("#{sort} #{@dir}")
		# else
		# 	@apartaments = House.paginate(:per_page=>per_page,:page => params[:page]).order("#{sort} #{@dir}")
		# end
	end

	
end

app/views/cabinet/hotels/_book_item.html.erb
                        <li class="car_item">
                            <ul class="item_elms">
                                <li class="desc">
                                    <a href="<%=cabinet_hotel_path(book.id)%>">
                                    <div class="lft"><img src="<%= book.img_url%>"  width="150" height="100"/></div>
                                    <div class="rt">
                                        <h3><%= raw book.hotel_name%></h3>
                                        <div class="rating"><span style="width:<%=book.stars*20%>%"></span></div>
                                        <p class="addr"><%=book.hotel_address%></p>
                                        <% unless true%>   
                                        <ul class="car_options">
                                            <% hotel[:options].each do |opt| %>
                                                <li>- <%=opt.gsub("Gratis trådlös Internet",t("all.hotels.free_wi_fi"))%></li>
                                            <%end%>                                            
                                        </ul>
                                        <%end%>   
                                        <span><%= strip_tags CGI::unescapeHTML(truncate(book.desc, length:150, separator: ' ',omission: '...'))%></span>
                                    </div>
                                    </a>
                                </li>
                            </ul>
                        </li>

app/views/cabinet/hotels/index.html.erb
        <div id="main_content">
            <div id="main" >
                <div id="main_wrap">
                    <%=render "cabinet/left_menu"%>
                <div class="right column">
                    <div class="text_content">
                        <% unless current_user.hotel_booking_payeds.any?%>
                            <h1><%=t("all.user.you_dont_book",:type=>t("search.cars_title").mb_chars.downcase)%></h1>
                        <% else%>
                        
                            <div class="text_body">
                                <ul>
                                    <%current_user.hotel_booking_payeds.each do |book|%>
                                        <%= render partial:"cabinet/hotels/book_item",:locals=>{:book=>book}%>
                                    <%end%>
                                </ul>
                            </div>
                        <%end%>
                        <div class="clear"></div>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="clear"></div>
                </div>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>

app/views/cabinet/hotels/index.html.haml
=render "cabinet/cabinet_header"
.clear	
#cabinet
	=render "cabinet/cabinet_orange_services"
	.clear
	.bookings_list
		- if @bookings.count < 1
			%h2.nothing_found=t("cabinet.not_found")
		- @bookings.each do |b|
			%a.item{:href=>cabinet_hotel_path(b),:style=>(@bookings.count < 3 ? "width:980px" : "")}
				%img{:src => "#{b.img_url}",:style=>"width:300px"}
				- if @bookings.count < 3
					%div{:class=>"item_desc"}=truncate(b.cancel_policy, length: 325, omission: '...')
				 
				%div{:class=>"item_status status_ico_#{b.status}"}
				.item_info
					.item_petriod
						%b="#{Date.parse(b.arrival_date).strftime("%d.%m.%y")} - #{Date.parse(b.departure_date).strftime("%d.%m.%y")}"
						%br
						= truncate b.hotel_name , :length=>25 , :omission=>"..."
					.item_price
						=t("cabinet.total_cost")
						%b="#{b.show_total_cost.to_i}#{@currency.symbol}"
						%br
						
					.clear
		.clear

app/views/cabinet/hotels/show.html.erb
        <div id="main_content">
            <div id="main" >
                <div id="main_wrap">
                    <%=render "cabinet/left_menu"%>
                <div class="right column">
                    <div class="text_content">
                        <%= render partial:"cabinet/hotels/book_item",:locals=>{:book=>@book}%>
                        <table>
                            <tr>
                                <th><%=t("all.book_date")%></th>
                                <th><%=t("all.dep_date")%></th>
                                <th><%=t("all.arr_date")%></th>
                                
                                <th><%=t("all.book_number")%></th>
                                <th><%=t("all.total_cost")%></th>
                            </tr>
                            <tr>
                                <td><%=l(@book.created_at,:format=>:long)%></td>
                                <td><%=l(Time.parse(@book.arrival_date),:format=>:long).gsub(", 00:00","")%></td>
                                <td><%=l(Time.parse(@book.departure_date),:format=>:long).gsub(", 00:00","")%></td>
                                
                                <td><%=@book.reservation_id%></td>
                                <td><%="#{(Exchange.convert(@book.base_currency, $currency) * @book.total_price.to_f).to_i}"%>
                                    <%=t("all.currencies_symbols.#{$currency}")%></td>
                            </tr>
                            
                        </table>
                        <table class="room_data">
                            <%@book.hotel_doc.each_with_index do |doc,i|%>
                            <tr>
                                <td style="color: #004b8d;font-size: 19px;padding: 0;margin: 0;"><%=t("all.hotels.rooom",num:i+1)%></td>
                            </tr>
                            <tr>
                                <td>
                                    <%=@book.room_desc%>
                                    
                                </td>
                                <td><%="#{doc.first_name} #{doc.last_name}"%></td>
                                <td><%=t("all.hotels.conf_num",num:doc.conf_number)%></td>
                                <td><%=t("all.hotels.r_status")%>: <%=t("all.hotels.r_status_#{doc.canceled.to_i}")%></td>
                            </tr>
                            <%end%>
                        </table>
                        <%if  false%>
                        <div class="pay_btn">
                            <a target="_blank" href="#"><%=t("all.cancel_book")%><span>></span></a>
                        </div>
                        <%end%>
                        <%if false%>
                            <h3><%=t("all.additional_book")%>:</h3>
                            <%@book.cars_extras.split(",").in_groups_of(@book.cars_extras.split(",").size/2,false).each do |ext_group|%>
                            <ul class="opton_group">
                                <%ext_group.each do |ext|%>
                                <li><%=ext%></li>
                                <%end%>
                            </ul>
                            <%end%>
                        <%end%>

                        <div class="rules">
                            <%=@book.cancel_policy%>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="clear"></div>
                </div>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>

app/views/cabinet/hotels/show.html.haml
=render "cabinet/cabinet_header"
#cabinet
  =render "cabinet/cabinet_orange_services"

  #apartments_booking{:"data-auto-controller"=>"HotelBooking"}
    %form{:action=>"/cabinet/hotels/booking_cancel"}
      %input{:type=>"hidden",:name=>"id",:value=>"#{@booking.id}"}
      .head_info
        %h2=t("front_all.your_book")
        %ul.list
          %li.book_image
            = image_tag( @booking.img_url ,:size=>"100x100")
          %li.width_250
            %h4=@booking.hotel_name
            %span=I18n.localize(Date.parse(@booking.arrival_date),:format=>:long)
            %span →
            %span=I18n.localize(Date.parse(@booking.departure_date),:format=>:long)
          %li.width_250
            %h4=t("front_all.destanation")
            %span #{@booking.hotel_address}
          %li
            %ul
              %li
                %span=t("front_all.check_in",:time=>"13:00").html_safe
              %li
                %span=t("front_all.check_out",:time=>"13:00").html_safe
          %li
            %h4=t("front_all.was_pay")
            %span
              = @booking.show_total_cost.to_i
            %span.currency
              = @currency.symbol
      .guests_data
        %h2=t("front_all.guests")
        .guest_block
          %ul.guests
            - @booking.hotel_doc.each do |room|
              %li.traveler
                %ul
                  %li.name=@booking.room_desc
                  %li.name 
                    #{room.first_name}
                  %li.name
                    #{room.last_name}
                  %li.name{:style=>( room.canceled ? "color:#ff793d;font-weight: bold;" : "")}
                    - if room.canceled
                      = t("front_all.room_canceled")
                    - else
                      = t("front_all.conf_number")
                      #{room.conf_number} 
      - unless @booking.canceled
        .book_block{:style=>"height: inherit;"}
          %h2=t("front_all.hotel_events")
          .block_info
            =@booking.cancel_policy
          .b_data_pay
            %ul.tickets_data
              %li.jNice{:style=>"z-index: 5;"}
                .left
                  %label=t("front_all.cancelation_type")
                  %select{:name=>"reason",:style=>"width:150px;"}
                    %option{:value=>"COP"}=t("front_all.cancelation_types.t_1") 
                    %option{:value=>"ILL"}=t("front_all.cancelation_types.t_2") 
                    %option{:value=>"DEA"}=t("front_all.cancelation_types.t_3") 
                    %option{:value=>"OTH"}=t("front_all.cancelation_types.t_4") 
                .left
                  %label Номер
                  %select{:name=>"room"}
                    - @booking.hotel_doc.each_with_index do |doc,i|
                      - unless doc.canceled
                        %option{:value=>i} Номер #{(i+1)}
      
          .buttons
            = link_to t("front_all.back") , cabinet_hotels_path,:class=>"grey"
            = link_to t("front_all.cancel_it") , "#",:class=>"pay to_cancel"