config/routes.rb
Cypr::Application.routes.draw do
  get 'admin',  to: "admin#index" 
  get 'logout', to: "users#exit"
  post "login",to: "users#auth"
  post "register", to: "users#register"
  post "restore", to: "users#forgot"
  get "fbregister",to:"users#fbregister"
  scope :path =>"(:locale)", :locale => /ru|ua|en/ do
    root :to => "home#index"
    get "hotels/show/:id" => "hotels#show"
    get "aparts/show/:id" => "aparts#show"
    get "hotels/load_hotels"
    post "hotels/booking/:id" => "hotels#booking"
    post "aparts/booking/:id" => "aparts#booking"
    post "hotels/book/:id" => "hotels#book"
    post "aparts/book/:id" => "aparts#book"

    get "hotels/pay"
    namespace :cabinet do 
        get :profile,to:"profile#show"
        get "offers/remove_photo",to:"offers#remove_photo"
        get "profile/edit",to:"profile#edit"
        put "profile/save",to:"profile#save"
        post "profile/save",to:"profile#save"
        resources :auto
        resources :offers
        resources :aparts
        resources :hotels
    end

    namespace "hotels" do
        %w(complete show booking results get_map_items).each do |action|
            get action
        end
    	post "search"
    	post "book"
    end
    namespace "avia" do
        %w(complete show booking results get_map_items).each do |action|
            get action
        end
        post "search"
        post "book"
    end
    namespace "cars" do
        %w(complete get_map_items show results dropp_off_open_time pick_up_open_time dropp_off_location dropp_off_city dropp_off_country pick_up_location pick_up_city).each do |action|
            get action
        end
    	post "search"
    	post "book"
    end
    get "cars/rules"
    get "cars/show/:id" => "cars#show"
    post "cars/booking/:id" => "cars#booking"
    post "cars/book/:id" => "cars#book"
    post "cars/pay"
    namespace "aparts" do
        %w(complete show results get_map_items).each do |action|
            get action
        end
        get "show/:id" => "aparts#show"
    	post "search"
    	post "book"
    end
    get "faq" ,to:"faq#index"
    get "faq/:seo" ,to:"faq#show"
  end






   namespace :admin do
     post "login_admin"
     post "users/pass_change"
     resources :users
     resources :emails 
     resources :transactions
     resources :facilities
     resources :apartaments
     resources :characteristics
     resources :currencies
     resources :nearbies
          resources :categories
     resources :pages
     get "apartaments",          to: "apartaments#index"
     get "apartaments/delete/:id",      to: "apartaments#delete"
     post "apartaments/upload_photos",  to: "apartaments#upload_photos"
     get "apartaments/remove_photo/:photo_id",  to: "apartaments#remove_photo"
     get "apartaments/remove_employment/:id",  to: "apartaments#remove_employment"
     get "apartaments/remove_price/:id",  to: "apartaments#remove_price"
     get "facilities",          to: "facilities#index"
     get "facilities/new",      to: "facilities#new"
     get "facilities/delete/:id",      to: "facilities#delete"
     get "nearbies/delete/:id",      to: "nearbies#delete"
     get "currencies/delete/:id",      to: "currencies#delete"
     get "characteristics",          to: "characteristics#index"
     get "characteristics/new",      to: "characteristics#new"
     get "characteristics/delete/:id",      to: "characteristics#delete"
     get "settings", to: "settings#index"
     post "settings/save"
   end






  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  	setup_models
    @pick_up_cities    = CarCity.where(lang:I18n.locale).all.map{|c|[c.name,c.id]}
    @hotel_cities      = HotelLocation.all.map{|c|[c.name,c.id]}
    @cities            = City.all.map{|c|[c.name,c.id]}
    @locations         = get_locations
    @pick_up_cities_all = CarCityLocation.where(lang:I18n.locale).all.map{|c|[c.name,c.location_id]}
  end

  def change_lang
  	
  end

  def change_currency
  	
  end

  private

  def setup_models
  	@hotels_search = HotelSearch.new(rooms:[HotelRoom.new(adult:[HotelAdult.new],child:HotelChild.new)])
  	@cars_search   = CarsSearch.new(:pick_up => CarsLocation.new(country:Country.find_by_code("CY").name) , :dropp_off=>CarsLocation.new(country:Country.find_by_code("CY").name,:date=>3.week.from_now.to_date.strftime("%d.%m.%Y")) , :driver_age=>nil)
  	@apart_search  = ApartSearch.new 
    @top_search    = TopSearch.new(rooms:[HotelRoom.new(adult:[HotelAdult.new],child:HotelChild.new)])
    @avia_search   = AviaSearch.new 
  end

  def get_locations
    {
      :apart_cities => City.all.map(&:to_map),
      :hotel_cities => HotelLocation.all.map(&:to_map),
      :cars_cities =>  CarCity.where(lang:I18n.locale).all.map(&:to_map)
    }
  end

end

app/views/home/index.html.erb
<script type="text/javascript">
    var locations = <%= @locations.to_json.html_safe %>
</script>
        <div class="choose_buttons action_div" data-action="set_active_tab">
            <ul>
                <li>
                    <a href="#main_map"><%=t("search.main_map")%></a>
                </li>
                <li>
                    <a href="#main"><%=t("search.main")%></a>
                </li>
            </ul>
        </div>
        <div id="main_content">
            <div id="main_map">
                <%=render "home/forms/top"%>
                <div id="g_map"></div>
            </div>
            <div id="main" >
                <div class="opacity"></div>
                <div id="main_wrap">
                    <div class="left column">
                        <div class="search action_div" data-action="set_active_form">
                            <h3><%=t("search.title")%></h3>
                            <ul class="list">
                                <li class="hotels active">
                                    <a href="#hotels"><%=t("search.hotels_title")%><em class="rectangle"></em></a>
                                </li>
                                <li class="cars">
                                    <a href="#cars"><%=t("search.cars_title")%><em class="rectangle"></em></a>
                                </li>
                                <li class="apartments">
                                    <a href="#apartments"><%=t("search.aparts_title")%><em class="rectangle"></em></a>
                                </li>
                                <li class="avia">
                                    <a href="#avia"><%=t("search.avia_title")%><em class="rectangle"></em></a>
                                </li>
                            </ul>
                            <div class="search_forms">
                                <%=render "home/forms/hotels"%>
                                <%=render "home/forms/cars"%>
                                <%=render "home/forms/aparts"%>
                                <%=render "home/forms/avia"%>
                            </div>

                        </div>

                    </div>
<!--                     <div class="right column">
                        <ul id="slider">
                            <li><%= image_tag "1.jpg" %></li>
                            <li><%= image_tag "2.jpg" %></li>
                        </ul>
                    </div> -->
                </div>

            </div>
        </div>

app/views/home/index.html.haml
%section.main
  %h1 Cyprus Short Stay
  %p We are opening soon....
  %a.btn_main{href: "#"}
    %span About Us
%nav
  %a.search{:href=>"#"}
  %ul
    %li
      = link_to "", apartments_path , :class=>"apartments"
    %li
      = link_to "", hotels_path , :class=>"hotels"
    %li
      = link_to "", cars_path , :class=>"cars"
    %li
      = link_to "", yahts_path , :class=>"yahts"

app/views/home/login.html.haml
=render "home/forms/login_form"
=render "home/forms/reg_form"
=render "home/forms/forgot_form"

app/views/home/routing.html.haml
#content{:style=>"width: 980px;margin: 100px auto;text-align: center;"}
  %h1{:style=>"color: #ff793d;font-size: 50pt;"} 404
  %h4{:style=>"color: #ffffff;font-size: 20pt;padding-top: 35px;"}=t("front_all.error_404")